#中央服务器IP地址
CentralServer-IP: 127.0.0.1:14514
#关于该MC服务器的信息
MinecraftServer:
  #用于验证连接的编号，账号和密码
  Net-ServerID: -1
  Net-Account: none
  Net-Password: none
  #玩家默认加入的频道ID，默认为1
  Net-DefaultChannelID: 1
#消息过滤模式：1为出现敏感词汇则整句消息屏蔽，2为遮挡敏感词，0为不做处理
Message-Filter-Mode: 1
Message-Filter:
  - "操你妈"
  - "傻逼"
#当频道持续一段时间没有收到消息，再次收到消息时会触发提示。以下为间隔时间设置(单位为秒)
#默认 3600秒 = 1小时
ShowTips: 3600
#玩家进服是否自动进入默认频道？
AutoJoinChannel: false
#频道消息格式
Channel-Message-Format: "§7[ §f%channelName% §7] [ §r%serverName% §r§7] [ §a%playerName% §7] §8» §7%message%"
#例子 Channel-Message-Format: "§f%channelName% §7| §r%serverName% §r§7| §a%playerName% §8» §7%message%"

#关于插件消息相关的，切记不要修改那些变量，否则会失效！
Language:
  CmdPrefix: "§8[ §6Vanilla-Network §8] §f"
  MsgPrefix: "§8[ §a香草网络 §8] §7"
  Plugin-Start: "%CmdPrefix% 正在初始化频道系统..."
  Plugin-Start1: "%CmdPrefix% 正在创建频道用户列表容器 [ 1/3 ]"
  Plugin-Start2: "%CmdPrefix% 正在创建频道消息队列 [ 2/3 ]"
  Plugin-Start3: "%CmdPrefix% 正在注册频道监听器 [ 3/3 ]"
  Plugin-Start-Finish: "%CmdPrefix% 频道系统初始化完成！"
  Server-GetInfo1: "%CmdPrefix% 正在获取所有服务器信息..."
  Server-GetInfo-Finish: "%CmdPrefix% 服务器信息加载完毕！"
  Command-Help:
    - "§7[ §f/ §7] §m----------"
    - "§8[ §a香草网络 §8] §f指令帮助 §7» "
    - "§7[ §f/ §7] §m----------"
    - "§b/vgc §8- §7查询指令帮助"
    - "§b/vgc channel §8- §7进入默认频道"
    - "§b/vgc channel [ 频道ID ] §8- §7进入指定频道"
    - "§b/vgc leave §8- §7离开频道，不再接收频道内消息"
    - "§7[ §f/ §7] §m----------"
  Command-Leave: "%MsgPrefix% 你已离开跨服频道！挥挥~"
  Command-Channel-Default: "%MsgPrefix% 你已进入 默认§f%defaultChannelID%频道 §8- §r%channelName%"
  Command-Channel-Default-Notfound: "%MsgPrefix% 未能找到 默认§f%defaultChannelID%频道§7！"
  Command-Channel-ID: "%MsgPrefix% 你已进入 §f%channelID%频道 §8- §r%channelName%"
  Command-Channel-ID-Notfound: "%MsgPrefix% 未能找到 §f%channelID%频道§7！"
