#修改Springboot服务端口
server:
  port: 14514
#在这里添加服务器，请确保每个服务器的ID都是独一无二的！其他的无所谓，不为空就行。
#可以添加无数个服务器！
mcserver:
  serverlist:
    - id: 1
      displayname: "§6狼与香辛料亭"
      account: "spiceandwolf"
      password: "yourpassword"
    - id: 2
      displayname: "§d璎珞"
      account: "yingluo"
      password: "anotherpassword"
    - id: 3
      displayname: "§2Miyazono的服务器"
      account: "miyazono"
      password: "wwwww"
#同上，也需要确保每个频道ID唯一！
#可以添加无数个频道！
channel:
  channelList:
    - id: 1
      displayname: "§d桃源仙境"
      announcement: "频道内与他人交流时请注意礼貌哦！|禁止在频道内打广告，违规引流。" # |是频道公告换行符哦，可以使用颜色符号§，默认白色
    - id: 2
      displayname: "§e矿工茶馆"
      announcement: "频道内与他人交流时请注意礼貌哦！|禁止在频道内打广告，违规引流。"